#!/bin/bash
# =============================================================================
# Fetch secrets from AWS Systems Manager Parameter Store
# Creates .env.prod file for docker-compose.prod.yml
# =============================================================================
# Usage: ./scripts/fetch-secrets.sh [--region us-east-1]
# Requires: AWS CLI configured with appropriate IAM permissions
# =============================================================================

set -euo pipefail

REGION="${1:-${AWS_REGION:-us-east-1}}"
PREFIX="/veradigm"
ENV_FILE=".env.prod"

echo "Fetching secrets from SSM Parameter Store (region: ${REGION})..."
echo "# Auto-generated by fetch-secrets.sh — $(date -u +%Y-%m-%dT%H:%M:%SZ)" > "${ENV_FILE}"
echo "# DO NOT COMMIT THIS FILE" >> "${ENV_FILE}"
echo "" >> "${ENV_FILE}"

fetch_param() {
  local name="$1"
  local env_key="$2"
  local value
  value=$(aws ssm get-parameter \
    --name "${PREFIX}/${name}" \
    --with-decryption \
    --query "Parameter.Value" \
    --output text \
    --region "${REGION}" 2>/dev/null || echo "")
  if [ -n "${value}" ]; then
    echo "${env_key}=${value}" >> "${ENV_FILE}"
  else
    echo "  WARN: ${PREFIX}/${name} not found, skipping ${env_key}"
  fi
}

echo "# ---- AWS Configuration ----" >> "${ENV_FILE}"
fetch_param "aws/account-id"       "AWS_ACCOUNT_ID"
fetch_param "aws/region"           "AWS_REGION"

echo "" >> "${ENV_FILE}"
echo "# ---- FHIR MCP Server ----" >> "${ENV_FILE}"
fetch_param "fhir/client-id"               "CLIENT_ID"
fetch_param "fhir/client-secret"           "CLIENT_SECRET"
fetch_param "fhir/base-url-sandbox"        "FHIR_BASE_URL_SANDBOX"
fetch_param "fhir/base-url-production"     "FHIR_BASE_URL_PRODUCTION"
fetch_param "fhir/auth-url-sandbox"        "AUTH_URL_SANDBOX"
fetch_param "fhir/token-url-sandbox"       "TOKEN_URL_SANDBOX"
fetch_param "fhir/auth-url-production"     "AUTH_URL_PRODUCTION"
fetch_param "fhir/token-url-production"    "TOKEN_URL_PRODUCTION"
fetch_param "fhir/token-cache-ttl"         "TOKEN_CACHE_TTL"
fetch_param "fhir/cache-enabled"           "CACHE_ENABLED"
fetch_param "fhir/log-level"               "LOG_LEVEL"

echo "" >> "${ENV_FILE}"
echo "# ---- Unity MCP Server ----" >> "${ENV_FILE}"
fetch_param "unity/app-name"               "UNITY_APP_NAME"
fetch_param "unity/svc-username"           "UNITY_SVC_USERNAME"
fetch_param "unity/svc-password"           "UNITY_SVC_PASSWORD"
fetch_param "unity/ehr-username"           "UNITY_EHR_USERNAME"
fetch_param "unity/ehr-password"           "UNITY_EHR_PASSWORD"
fetch_param "unity/ubiquity-endpoint"      "UNITY_UBIQUITY_ENDPOINT"
fetch_param "unity/ubiquity-id-pm"         "UNITY_UBIQUITY_ID_PM"
fetch_param "unity/ubiquity-id-ehr"        "UNITY_UBIQUITY_ID_EHR"
fetch_param "unity/token-cache-ttl"        "UNITY_TOKEN_CACHE_TTL"
fetch_param "unity/token-refresh-buffer"   "UNITY_TOKEN_REFRESH_BUFFER"

echo "" >> "${ENV_FILE}"
echo "# ---- Admin Portal ----" >> "${ENV_FILE}"
fetch_param "admin/db-password"            "DB_PASSWORD"
fetch_param "admin/nextauth-url"           "NEXTAUTH_URL"
fetch_param "admin/nextauth-secret"        "NEXTAUTH_SECRET"
fetch_param "admin/email"                  "ADMIN_EMAIL"
fetch_param "admin/password"               "ADMIN_PASSWORD"
fetch_param "admin/api-key"                "ADMIN_API_KEY"
echo "DOCKER_SOCKET_PATH=/var/run/docker.sock" >> "${ENV_FILE}"

echo ""
echo "Secrets written to ${ENV_FILE}"
echo "Run: docker compose -f docker-compose.prod.yml up -d"
